/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'jrbraaten' at '1/28/17 10:35 PM' with Gradle 2.14.1
 *
 * @author jrbraaten, @date 1/28/17 10:35 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
